// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS-nYXiMiJ9vxPMeTAGFOMcKJGH6b3ldQ',
    appId: '1:238864067018:web:722ca9d749d286ab414733',
    messagingSenderId: '238864067018',
    projectId: 'interview-2d053',
    authDomain: 'interview-2d053.firebaseapp.com',
    storageBucket: 'interview-2d053.appspot.com',
    measurementId: 'G-FVRFRFSJX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoW-aqRDlgK50blywTmC6F5Pj3yLx5LAM',
    appId: '1:238864067018:android:c1c1d8d35ecaab8d414733',
    messagingSenderId: '238864067018',
    projectId: 'interview-2d053',
    storageBucket: 'interview-2d053.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArdvReXAg-gR6d4rWauSFJj9SJrf0h38c',
    appId: '1:238864067018:ios:018a3921f860c92a414733',
    messagingSenderId: '238864067018',
    projectId: 'interview-2d053',
    storageBucket: 'interview-2d053.appspot.com',
    iosBundleId: 'com.example.interviewPrg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArdvReXAg-gR6d4rWauSFJj9SJrf0h38c',
    appId: '1:238864067018:ios:018a3921f860c92a414733',
    messagingSenderId: '238864067018',
    projectId: 'interview-2d053',
    storageBucket: 'interview-2d053.appspot.com',
    iosBundleId: 'com.example.interviewPrg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS-nYXiMiJ9vxPMeTAGFOMcKJGH6b3ldQ',
    appId: '1:238864067018:web:9b054ce6f687a905414733',
    messagingSenderId: '238864067018',
    projectId: 'interview-2d053',
    authDomain: 'interview-2d053.firebaseapp.com',
    storageBucket: 'interview-2d053.appspot.com',
    measurementId: 'G-3F3Q6WNHJD',
  );
}
